---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "sync.fullname" . }}
  labels:
    {{- include "sync.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "sync.selectorLabels" . | nindent 4 }}
  ports:
    - name: web
      protocol: TCP
      port: 8384
      targetPort: 8384
    - name: tcp
      protocol: TCP
      port: 22000
      targetPort: 22000
    - name: udp
      protocol: UDP
      port: 22000
      targetPort: 22000
    - name: lan-discovery
      protocol: UDP
      port: 21027
      targetPort: 21027
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "sync.fullname" . }}-headless
  labels:
    {{- include "sync.labels" . | nindent 4 }}
spec:
  clusterIP: None
  selector:
    {{- include "sync.selectorLabels" . | nindent 4 }}
  ports:
    - name: web
      protocol: TCP
      port: 8384
      targetPort: 8384
    - name: tcp
      protocol: TCP
      port: 22000
      targetPort: 22000
    - name: udp
      protocol: UDP
      port: 22000
      targetPort: 22000
    - name: lan-discovery
      protocol: UDP
      port: 21027
      targetPort: 21027

